name: lost_and_found_web
description: A new Flutter project.

dependencies:
  flutter_spinkit: ^4.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  geolocator: ^5.2.1
  http: ^0.12.0+4
  image_picker: 0.6.3+1
  firebase_storage: ^3.0.3
  firebase_ml_vision: ^0.9.3+8
  image_cropper: ^1.2.1
  animated_text_kit: ^1.3.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  email_validator: ^1.0.0
  firebase_analytics: ^1.0.4
  firebase_messaging: ^6.0.16
  fluttertoast: ^4.0.1
  flutter_local_notifications: ^1.4.3
  transparent_image: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo.png"
flutter:
  uses-material-design: true
  assets:
    - images/
    - logo.png
    - logo2.png
    - Custom-Logos.png
    - ashok.jpg
    - no_image.png